PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/micromax/spark/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/micromax/spark/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/micromax/spark/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/micromax/spark/vendor,system/vendor)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/micromax/spark/xbin,system/xbin)
